### PR TITLE
Make SqlQuery cancel asnyc, and add a cancel timout, which upon firing actively destroys the database connection to un-block the original thread.

### PR DESCRIPTION
**Pull request by freels**
Name says it all, though I'm not sure how to automatically test this behavior. Manually tested and confirmed that this works.

### CODE REVIEW

**Comment by robey** [comment]
i think this should be moved into TimingOutQuery (which i just said on aim). also i would import the classes you use from dbcp & jdbc, so they don't have the full-out class names in the code. looks good besides that.

**Comment by eaceaser** [comment]
yeah. TimingOutQuery should probably attach the timeout behavior around cancel that then deelgate down to the actual SqlQuery.

**Comment by freels** [comment]
moved to TimingOutQuery. also TimingOutStatsCollectingQuery is crazy.

**Comment by robey** [comment]
hahaha yes it is. :)

+1 on the patch!

**Comment by freels** [comment]
cool. I don't have commit rights, so someone else needs to give them to me or integrate :)

**Comment by freels** [comment]
this is in release 1.2.0

**Pull request closed without merging**
